### ISSUE TITLE
Does not work on Firefox Developer edition (37.0a2 (2015-02-08)) on Ubuntu 14.04

### ISSUE THREAD

**Issue by davidstosik** [mmouterde/FlexyTrello#14]
Hello,

I finally found a proper way to file an issue, sorry for writing a bad review the first time...
Original comment:

> This plugin does not seem to work on Firefox Developer edition . I'm also using Trello improvements (https://addons.mozilla.org/en-US/firefox/addon/trello-improvements).﻿

And a follow up: I tried the new version (1.1.6), I still don't get any "FlexyTrello" icon that would allow me to enable the plugin and resize Trello columns. I also looked for the icon in Customize, didn't find it.
By the way, I'm on Ubuntu 14.04.

Thanks,

David

**Comment by davidstosik** [comment]
So for my first test, I didn't restart Firefox as the plugin states it's not necessary.
I even tried to refresh my Trello board, or to open it in a new tab, and got nothing.
I eventually restarted my browser, and the drag&drop resize corners and reduce/expand -/+ buttons appeared on my board.
Apparently, contrary to the Chrome version, the Firefox version does not need the user to click on an icon in the address bar to be enabled, am I right?

**Comment by mmouterde** [comment]
Thanks for reporting here

You are right, I have to update the video for chrome and make one for Firefox.
By default, Firefox does not provide a way to add url icon.

Thanks for your new review note on addons.mozilla.org
