### ISSUE TITLE
Collapse buttons sometimes do no appear

### ISSUE THREAD

**Issue by mika76** [mmouterde/FlexyTrello#16]
The minus button is sometimes just not there. I do also use the scrum for trello addin (https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje?hl=en) so that might be a problem? Still, if I refresh they come back.

**Comment by mmouterde** [comment]
Thanks for reporting.
The next version (comming soon) already includes a fix for such errors.

**Comment by JoelAzaria** [comment]
I have similar problem too.  I think the first time I display a trello page the min buttons do not show.  After I do a refresh they show.  I think this is repeatable every time but I need to test.  When do you expect the next release?

**Comment by mika76** [comment]
Coming soon was like a month ago, do you have a date when it's gonna come out?

**Comment by mmouterde** [comment]
1.1.6 released  !
Please test your use-cases and let me known.

**Comment by JoelAzaria** [comment]
So far so good!  Great work, thx!

-------  Follow up:

So I've opened/closed trello windows a dozen times and refreshed a window a couple dozen times so far and it works just fine.  Very very nice!

Now just work out persistent states for minimized and List width (cookies maybe?) and this thing will be complete!  Thanks for your efforts friend!
