### ISSUE TITLE
Page refresh in Chrome causes some cards to shrink in size

### ISSUE THREAD

**Issue by tomgiorgio** [mmouterde/FlexyTrello#19]
The extension works great, but if I leave my boards at normal width and refresh the page, some of my cards become smaller than normal. Screenshot: http://i.imgur.com/CgNEKFo.png

Apologies for the hasty blurring

**Comment by mmouterde** [comment]
Thanks for reporting : A screenshot is better than a huge description !

I've just released a new version (1.1.6). This bug should be fixed.
Please, could you test ?

**Comment by tomgiorgio** [comment]
Yep all good! Thanks!
