### ISSUE TITLE
Width Stepper fails

### ISSUE THREAD

**Issue by mmouterde** [mmouterde/FlexyTrello#24]
from : @JoelAzaria 

Ok, good effort.  It fixes the refresh issue when dragging cards or re-sizing columns, so that's good but I'm having an issue where when I increase the column size (say to 2 col) the list expands but not quite wide enough for two cols of cards so I have a two col wide list but just one col of cards in it.  It's probably short by just a few pixels but it's kinda weird.  Consequently if I hit increase again the list bumps to three wide and two cols of cards. If I go up to 4 cols it seems to catch up (parity) and reducing to 3 and 2 cols seems to stay matched (cols vs list width) so might be just a slight math glitch.

Either way, please have a look.  So far great work and it seems to be coming together so thanks for your efforts.

See screencap:
![clipboard01](https://cloud.githubusercontent.com/assets/470908/7816991/b819c200-039f-11e5-9cd8-4fab4887a00c.jpg)

**Comment by mmouterde** [comment]
I can not reproduce... 
What is your screen resolution ?
Which other trello plugins do you use ?

**Comment by JoelAzaria** [comment]
Seeing is believing..  happens for me pretty consistently.

2 screens @ 1920x1080, happens on either one.

Enabled extensions =
Flexytrello
Projects for trello
Ultimello

**Comment by mmouterde** [comment]
It's not a matter of believing or not.. I can not measure missing pixels if I don't meet the problem...
I have the same resolution, same extension and not the problem ;oz

**Comment by mmouterde** [comment]
Please, let me know once you get the 1.3.2

**Comment by JoelAzaria** [comment]
Sorry, the "seeing is believing" comment was just me being humorous..

Looking for 1.3.2 now.  willl report back with any issues, thanks.

---

Ok, just tested.  Same issue. :(

**Comment by JoelAzaria** [comment]
Ok, update - I found the "cause" of the problem.  My browser is set to zoom level 75%.  I have no problem at 90% or 100% zoom so that's good I guess.  But I use trello at 75% zoom pretty much all the time.  So I hope you can get it fixed so it works at all zoom levels (or at least 75% too).

Thanks for your efforts.

**Comment by JoelAzaria** [comment]
Ok, update to the update - zoom level is not the only factor.  I have a list in another board for job applicants.  We put their profile photo on each card so every card in this list has a cover picture.  On this board with these cards, at any zoom level I get left with a blank column.  I think the width of the Trello cards may not be strictly fixed?  Do they get wider when they have image covers on them?

hth.

**Comment by mmouterde** [comment]
Thanks for investigating !
I think i got it : It depends on the vertical scrollbar visibility.

**Comment by mmouterde** [comment]
fix published. Please Let me know.

**Comment by JoelAzaria** [comment]
Ok, kudos!  We have progress!  :)

So the fix works at 100% zoom and at 90% zoom (I even disabled the extension, refreshed, re-enab led and refreshed and retested a dozen times)  but at 75% zoom I still have an issue on the board where every card has images.  On my GTD board (images only on some cards) it seems to work at 75% too.

Hoping you can solve this across different zoom levels and content.  I really only use trello at 75% zoom so as good as it is, it's still broken for me :(

Thanks for efforts.  It's so close yet for me sooo far, lol.  REALLY hoping you can figure something out!
