### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Abhishekgoel1503** [mmouterde/FlexyTrello#25]
I use chrome Version 43.0.2357.130 m 

Flexy has stopped working.
I have tried refreshing a lot number of times, uninstalled and reinstalled as well , but it doesn't work.

It just shows the arrows to expand or contract but doesn't acutally do that.
Please help as the extension is a life saver

**Comment by mmouterde** [comment]
Absolutely ! Thanks for reporting.
Trello has been released with impacting changes.
A fix is published, let me know when you could test the 1.3.4 version.

**Comment by Alsachi** [comment]
I have the same problem. Flexy has stopped working.

**Comment by mmouterde** [comment]
Did you try to reset your layout (by clicking on the URL FlexyTrello icon), then refresh ?
That's still working for me. Any others clues ?
