### ISSUE TITLE
When resizing a list, other lists don't move

### ISSUE THREAD

**Issue by jpfleury** [mmouterde/FlexyTrello#26]
On Firefox 40.0.3, I've installed the file `firefox/flexytrello.xpi` from the archive https://github.com/mmouterde/FlexyTrello/archive/1.3.4.zip. I'm not sure I've really installed the version 1.3.4 because in the file `install.rdf`, it's written:

```
<em:version>1.1.6</em:version>
```

so it is in about:addons:

![capture d ecran_2015-09-03_12-45-12](https://cloud.githubusercontent.com/assets/687082/9664712/a62103d6-5239-11e5-83a3-4c0c3c8be085.png)

Anyway, when I resize a list, other lists don't move, so the resized one is half hidden:

![resized list](https://cloud.githubusercontent.com/assets/687082/9664616/170237b0-5239-11e5-89d7-6f9cc678a827.png)

Since the demo video doesn't work, I don't really know how this addon is supposed to work, so i don't know if I'm doing something wrong or if there's a bug.

**Comment by mmouterde** [comment]
Thanks for reporting.
Actually, the Firefox version is not supported any more (no time for this).
Anyway, this new bug also happens on chrome.

**Comment by JoelAzaria** [comment]
Is this being worked on?  This bug is not intermittent (at least not for me) making the extension unusable.
thx.

FYI, issue #27 looks like a dup (or close relation) to this one.

**Comment by mmouterde** [comment]
closed : Initially this issue was about unsupported FF version.
As @JoelAzaria said, the chrome bug is reported as #27
