### ISSUE TITLE
When collapsing a list - the other lists do not move closer

### ISSUE THREAD

**Issue by mika76** [mmouterde/FlexyTrello#27]
They just stay in the same place - so then you are left with a big space between the collapsed (vertical) list and the next list.

**Comment by JoelAzaria** [comment]
I believe this is the same bug as #26.

**Comment by mmouterde** [comment]
I've released. Please let me known when you get 1.3.5

**Comment by JoelAzaria** [comment]
Only tested briefly but I'm happy to report this is working for me.
Will report if I run into any issues but so far, job well done.  :+1: 

Follow up 4/30/16 -- 
Now working well for a while.  Does what it says on the tin. Great work.  Thank you.

**Comment by mmouterde** [comment]
thanks !
