### ISSUE TITLE
Collapsed List not aligned on top

### ISSUE THREAD

**Issue by mmouterde** [mmouterde/FlexyTrello#3]
Sometime List are not aligned on top ?!

![notaligned](https://cloud.githubusercontent.com/assets/733538/5929133/407730f0-a681-11e4-8842-de0b1cb8eb4e.png)

**Comment by mmouterde** [comment]
When you use extension "Plus for Trello", you do not meet this issue.

**Comment by ghost** [comment]
List are not aligned on top. This problem persist on version 1.1.4 
https://www.uploady.com/#!/download/F6uDp2TW97b/LEBQVbiIL4fMPQOE

Chrome Version 40.0.2214.94 m (64-bit)

**Comment by mmouterde** [comment]
I do not reproduce this bug on this board :(
- If you make some F5 / Ctrl-F5 does this problem persist ? (I suspect the new auto-load feature to init dimensions too early when some cache is used)
- Are you sure to be up to date (1.1.4) ? I just publish it 7h ago

**Comment by ghost** [comment]
Confirmed ver 1.1.4, the problem persist after some F5 . Maybe there is some conflict with other extensions . I'll make some inquiries

**Comment by mmouterde** [comment]
Reproducted !
I had to remove all my trello extensions.

Thanks for reporting and tests !

**Comment by ghost** [comment]
Thanks :)
