### ISSUE TITLE
Column Width Bug

### ISSUE THREAD

**Issue by Mochnant** [mmouterde/FlexyTrello#30]
Chrome v58.0.3029.96 (64-bit)
FlexyTrello v1.3.6
I have not enabled persistence.

If you widen a column to 2, and then the page is refreshed, or you change boards, the column returns to 1 (which is expected without persistence).  However, when you widen it to 2 again, it actually skips 2 and goes to 3.  This is reproducible.

You can avoid this by manually sizing the column back to 1 before leaving the board/refreshing, and then it expands normally.

**Comment by mmouterde** [comment]
I got it.
Even worse : the first time it grow to 2, then to 3...

**Comment by Mochnant** [comment]
That is true, too!  It is clearly remembering something of the previous configuration, even though it is not persistent.

Would be nice if the fix would be remembering the configuration at least for the sessions.  For some reason I find the permissions required for for persistence to be a little to scary to use.

**Comment by mmouterde** [comment]
yep.
I did not test/use the extension disabling persitence...

In any case, there is no way to identify a column when persistence is disabled. I can not save "last" sessions.
If I could avoid persitence option I would...

thanks for reporting !

**Comment by mmouterde** [comment]
I've just published a fix. Please tell me.

**Comment by Mochnant** [comment]
I can confirm this works, thank you!
