### ISSUE TITLE
When Collapsing Columns Menu Pops Up

### ISSUE THREAD

**Issue by Mochnant** [mmouterde/FlexyTrello#31]
FlexyTrello 1.3.7
Chrome 58.0.3029.110 (64-bit)

I've noticed when using minus (-) in the column header to collapse, it often erroneously triggers the popup menu called "List Actions" which includes items like "Add Card", "Copy List","Move List" etc.  This menu is normally triggered with the (...) in the header, so this may be an issue with the click location.

See image:

![screen shot 2017-05-18 at 2 47 30 pm](https://cloud.githubusercontent.com/assets/746190/26218519/429dd7ae-3bd9-11e7-8245-655245ded3cd.png)

**Comment by Mochnant** [comment]
I've noticed to reproduce, you need to click on the (...) first to open the List Actions menu at least once.  Then close it and for the rest of that session clicking the (-) will also trigger the List Actions menu.  Refreshing the browser resets it.

**Comment by mmouterde** [comment]
Ok, thanks for reporting !

**Comment by mmouterde** [comment]
Let me know when you get the 1.3.8 version

**Comment by Mochnant** [comment]
I can confirm it is fixed, thank you!
