### ISSUE TITLE
[Feature Request] Column Card Counts

### ISSUE THREAD

**Issue by Mochnant** [mmouterde/FlexyTrello#32]
With the ability to collapse columns, it would be very useful to have a way to see the count when collapsed integrated into FlexyTrello.

**Comment by mmouterde** [comment]
Do you mean to have the number of cards in collapsed column ?!
Did you try : https://chrome.google.com/webstore/detail/trello-card-counter/bodefgeflaobkeejlcbbnbniimlinocd?hl=fr

**Comment by Mochnant** [comment]
I have used that exact one, but it works by changing the column title, and is prone to glitches like "To Do (5) (6)" etc, and the number is also visible in other places that reference the column name.  I think it would be better to do it in a more elegant way that doesn't use the title.

Seems like a minor change that would be a good fit for Flexy, but I totally understand if you'd rather focus on what you do best.

**Comment by mmouterde** [comment]
It's true, I have all required info to add numbers of cards in collapsed column, but I prefere to focus.
However, I think it would be useful to get the number of hidden cards.

What about : https://chrome.google.com/webstore/detail/cardcounter-for-trello/miejdnaildjcmahbhmfngfdoficmkdhi

I can change FlexyTrello to not hide these counters ?!

**Comment by Mochnant** [comment]
Visually I think that one would work fine, but I was put off by some of its behavior as reported by a reviewer:

> Everytime you visit trello.com, this extension sends your Trello's username, full name, email, bio, and avatar to https://cardcounter.codability.nl/save.php. There's no reason for the author of this script to collect this information. The author doesn't mention this information is collected as well.
> 
> You can look through the extension's source code yourself by looking up how to view Chrome Extension Source Code.

**Comment by mmouterde** [comment]
ok, forget about this unfair extension.
I will do the job.

**Comment by Mochnant** [comment]
I really appreciate you digging into this, thank you.

**Comment by mmouterde** [comment]
let me know

**Comment by Mochnant** [comment]
@mmouterde Unfortunately using 1.3.9 I can't seem to see any of the FlexyTrello controls.  I believe I can see a flicker of a lighter color square where the collapse control would be, but when the page loads, I see no sign of Flexy.  I've tried both with and without persistence.

**Comment by mmouterde** [comment]
oops 1.3.10 would be better

**Comment by Mochnant** [comment]
That is a great improvement, thank you!  Looks very nice!

Have you considered a count on the open tabs?  The collapsed was most important but both might benefit.

Thanks again!

**Comment by mmouterde** [comment]
I have finally removed counters from FlexyTrello.

Please try instead : https://chrome.google.com/webstore/detail/trello-card-counter/lkifhkgedjabhdpbogaobhkgajndjihg

This is a new extension from me witch is integrated with FlexyTrello

**Comment by Mochnant** [comment]
Fantastic, @mmouterde!  Thank you so much!
