### ISSUE TITLE
Board switch bug

### ISSUE THREAD

**Issue by payling** [mmouterde/FlexyTrello#33]
Clicking the Trello "Boards" button in top left corner then a different board causes Flexy features to disappear. The min, max, and resize Flexy buttons that normally appear on cards are gone after the newly selected board loads.

If I reload the page using CTRL + R Flexy features reappear. My guess is Flexy code is not detecting the board switches when using Trello's "Boards" button. 

I'm using Chrome Version 59.0.3071.104 (Official Build) (64-bit).
FlexyTrello 1.3.11

**Comment by mmouterde** [comment]
Hy, thanks for reporting !
You are right, I did not find a proper way to detect board switches...

**Comment by mmouterde** [comment]
let me know when you get the new version 1.3.12

**Comment by payling** [comment]
Bug gone in version 1.3.12

Thanks Martin
