### ISSUE TITLE
FlexyTrello Not Working/Controls Not Visible

### ISSUE THREAD

**Issue by Mochnant** [mmouterde/FlexyTrello#34]
Chrome: Version 59.0.3071.115 (Official Build) (64-bit)
FlexyTrello: 1.3.12
Card Counter: 1.01

Today after a page refresh, I noticed FlexyTrello appears to not be working property.  I am not sure what has caused it (Chrome, Trello or FlexyTrello update?), but none of the controls appear.  When I refresh the page, I can see for a moment what looks like a box where the collapse element might be drawn before it disappears.

I have tried restarting Chrome and reinstalling the extension to no avail.

**Comment by mmouterde** [comment]
Thanks for reporting !
Trello has been released with breaking change. 
I fixed this on FlexyTrello 1.3.13, let me know when you get this release.

**Comment by Mochnant** [comment]
@mmouterde I can confirm FlexyTrello is working again, thank you!
