### ISSUE TITLE
Column Width Error When Using Trello Move Action

### ISSUE THREAD

**Issue by Mochnant** [mmouterde/FlexyTrello#35]
Chrome 59.0.3071.115 (Official Build) (64-bit)
FlexyTrello 1.3.13
Trello Card Counter 1.0.1

Dragging cards works, but if I use the Trello card Action -> Move and select position 1, when I move it, the column widths expand incorrectly.  Refreshing the page returns them to the correct width.

Specifically, I had a 3 width column become 5, and two 2 width become 4 width.

This is reproducible.

Thank you.

**Comment by mmouterde** [comment]
hum, sorry but I can reproduce this issue... no other plugins ? actions ?

**Comment by Mochnant** [comment]
I am still able to recreate this after restarting/etc.  It seems to you need to move it into position 1 when there are multiple cards, and more than one column.  At least that is how I am doing it.

I don't have any other extensions running that seem relevant (uBlock Origin and JSONView).

**Comment by Mochnant** [comment]
An additional clue is that if you move multiple cards, it seem to keep expanding the columns.  I was able to do it by using Action -> Move, and changing the position only (not the List).  Each card moved seemed to be +1 column width.

**Comment by mmouterde** [comment]
I guess I got it.
Do you observe two "-" (minus button) ?

![image](https://user-images.githubusercontent.com/733538/29188474-733ebf96-7e13-11e7-9701-f11b77479642.png)

**Comment by Mochnant** [comment]
Excellent!  I had not noticed until you mentioned it, but testing it again, I can confirm there are 2 after the first column widening.

The minuses do increase past 2 if you continue using Move.

![screen shot 2017-08-10 at 3 34 55 pm](https://user-images.githubusercontent.com/746190/29188611-9fb23abc-7de1-11e7-915d-fc2470c4b2d5.png)

**Comment by mmouterde** [comment]
Cool ! thanks.

I had to change the way I handle the board changing. I usually track the URL.. but switching from board to card change the entire URL from now...

**Comment by Mochnant** [comment]
Thanks for taking the time to fix it!

**Comment by mmouterde** [comment]
Let me known when you get the 1.3.14
