### ISSUE TITLE
FlexyTrello not loading on first page load

### ISSUE THREAD

**Issue by MumbleMurmur** [mmouterde/FlexyTrello#36]
When loading into one of my Trello boards, FlexyTrello does not engage. Even switching from one board to another does not trigger the load; only after I refresh the page does FlexyTrello start to work. Could be similar to #33.

**Comment by mmouterde** [comment]
Thanks for reporting !

I can't reproduce this issue... Could you please verify the options of the plugin ? I guess the Trello credential are disabled for you.
