### ISSUE TITLE
Page refresh with filter on leads to strange two-column layout

### ISSUE THREAD

**Issue by ro6** [mmouterde/FlexyTrello#37]
If I reload the page with filters on I end up with this strange squashed two-column layout. Deactivating the filter and refreshing the page again seems to fix it.

Google Chrome | 64.0.3282.24 (Official Build) beta (64-bit) (cohort: Beta)
-- | --
Revision | b0ff7139cae6db3e8c340bea7a081b73d00a342c-refs/branch-heads/3282@{#161}
OS | Windows
JavaScript | V8 6.4.388.5

Before:
![image](https://user-images.githubusercontent.com/8773802/34090358-4b52bc9a-e36b-11e7-8445-b5b8674f1d40.png)

After:
![image](https://user-images.githubusercontent.com/8773802/34090314-e01ed40e-e36a-11e7-8d14-c37a9b97c5f8.png)

**Comment by mmouterde** [comment]
thanks for reporting !
You are right. I have to investigate.

**Comment by mmouterde** [comment]
fixed it in 1.3.15
Let me know when you get this version.

**Comment by ro6** [comment]
@mmouterde I have 1.3.15. I tested and the issue remains.

**Comment by mmouterde** [comment]
Trello filters have changed. I can not reproduce the issue.
