### ISSUE TITLE
Changes are not saved

### ISSUE THREAD

**Issue by kjim14** [mmouterde/FlexyTrello#38]
Hey guys, I LOVE this app. The functionality is amazing but whenever I switch to a different Trello account or refresh the Chrome browser, the collapsed or expanded lists go back to their normal state. In other words, the changes FlexyTrello makes are not saved. Any ideas as to what might be going on?

**Comment by mmouterde** [comment]
Trello settings (collapsed/expanded) are specific to one trello account. 
There is no proper way to keep settings across different accounts.

**Comment by mmouterde** [comment]
Did you authenticate in the extension options ? This is required to store settings.
