### ISSUE TITLE
Display issues with other extension

### ISSUE THREAD

**Issue by duckwagon** [mmouterde/FlexyTrello#41]
The bottom bar with the 2-column-expansion button is too tall, obscures the bottom of the card list, and makes it difficult to manage cards with the multiple row view of [List Layouts for Trello](https://chrome.google.com/webstore/detail/list-layouts-for-trello/aldklnbenbdgfgfbflalmlddkkndgnlc).

The top bar will often have several expand/contract buttons which overlays the list title, or other buttons if added. 

This likely has to do with [List Layouts for Trello](https://chrome.google.com/webstore/detail/list-layouts-for-trello/aldklnbenbdgfgfbflalmlddkkndgnlc). At the least, the first issue. I don't know on which side the issue lies. Other culprits may be: [Pro for Trello](https://chrome.google.com/webstore/detail/pro-for-trello-free-trell/hcjkfaengbcfeckhjgjdldmhjpoglecc); [Trellists](https://chrome.google.com/webstore/detail/trellists-trello-lists-ma/dgnlcodfeenegnifnpcabcclldoceeml); or [Ultimello](https://chrome.google.com/webstore/detail/ultimello-the-features-pa/hahbfgjfimnmogoinnenhheepfcphnmm).

Edit: I'm on the latest version of chrome, on OSX High Sierra, if that helps.

**Comment by mmouterde** [comment]
Sorry I can not support every plugin that could be in conflict with FlexyTrello.
Feel free to contribute ^^
