### ISSUE TITLE
Recent update seems to have broken flexy

### ISSUE THREAD

**Issue by Omarcito** [mmouterde/FlexyTrello#43]
Flexy no longer loads for us. Im assuming something was updated on trello that broke the hooks. if anyone could get it loading again that would save me. thanks

**Comment by Mochnant** [comment]
Just dropped in to report the same thing.  Hopefully @mmouterde can fix it!

**Comment by Omarcito** [comment]
@Mochnant I was clicking around the area the Flexxy arrows should be at the bottom of the list out of desperation and my list expanded! I guess the arrows just don't show at page load? After clicking around down there everything seems to be back to normal until I reload the page but the furious clicks bring it back. Hopefully that works for you too.

**Comment by Mochnant** [comment]
Thanks for the tip, @Omarcito.  I just tried the clicking but couldn't make it work, unfortunately.

**Comment by skiutpow** [comment]
Unfortunately confirming the above posts that this is an issue. **This is a very useful extension** - I really hope @mmouterde can fix or advise others on how to fix (alas, I for one am simply a user and not a developer).

**Comment by mmouterde** [comment]
I published a fix : 1.3.16
please let me know.

**Comment by skiutpow** [comment]
HUGE thanks - really appreciate it!

**Comment by Mochnant** [comment]
I can confirm it is working again, thank you, @mmouterde!

**Comment by mmouterde** [comment]
Thanks for reporting 😅

**Comment by chigh** [comment]
Another confirmation. It's working again. Thanks! 👍

**Comment by Mochnant** [comment]
Reporting is the easy part, thanks for maintaining this very useful plugin, @mmouterde.

**Comment by jantje1973** [comment]
@mmouterde 
The plugin is "working again", which is great....but:
Unfortunately only the first 7 lanes can be resized.
See screenshot
![image](https://user-images.githubusercontent.com/48959036/55013350-3e238400-4fe9-11e9-911c-7a80c6aee487.png)

**Comment by shairryn** [comment]
Seeing the same issue for me as well.  Only the first 6 lanes can be collapsed or resized.  Thanks!

**Comment by mmouterde** [comment]
@shairryn @jantje1973 I got it.
Working on #42 soon
