### ISSUE TITLE
Support for Mozilla Firefox

### ISSUE THREAD

**Issue by Atomy9** [mmouterde/FlexyTrello#44]
Hello

Apparently this extension used to be available on the [Firefox Addons store here](https://addons.mozilla.org/fr/firefox/addon/flexytrello/). 
But now it doesn't seem to be available anymore. What happened ? Are there any plans to support this version again ?

I personally can't use Trello without this extension but would love to switch to Firefox.

**Comment by mmouterde** [comment]
Technically the gap to make it works on Firefox is really simple : It's essentially a matter of packaging.

I used to deploy on both browser store but, It takes too much time to deploy and test. I have failed several times to support Firefox and to maintains the quality. As I don't use Firefox, I decided to leave Firefox.

Feel free to contribute and help me to maintain the firefox version ^^
Trello deploys at random frequency, but is quite stable and it takes me about few hours every tree months.

**Comment by Atomy9** [comment]
I'm not very good but I can try. If you have some documentation / notes from when you used to support the extension, I'd be glad to have a look.

**Comment by mmouterde** [comment]
This could be a good first step :
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by LoneDev6** [comment]
Any news on this? Seems that it's not available anymore on addons website https://addons.mozilla.org/fr/firefox/addon/flexytrello/
