### ISSUE TITLE
Error trying to enable persistence

### ISSUE THREAD

**Issue by nBerg** [mmouterde/FlexyTrello#46]
I receive the following image when I trying to click "authorize" to enable persistence:

<img width="831" alt="Screen Shot 2020-06-25 at 7 31 59 PM" src="https://user-images.githubusercontent.com/2374174/85805547-a4321600-b71a-11ea-9868-3fca6e7715dd.png">

**Comment by mmouterde** [comment]
Thanks for reporting !
I get the same error. From my first investigation, this is due to a chrome new security policy.
I'm working on a workaround.

**Comment by mmouterde** [comment]
OK Got it ! Please let's try when you get the 1.3.18 and let me know

**Comment by nBerg** [comment]
Thank you!
