### ISSUE TITLE
Trello wildcard origin not supported when authorising for persistence

### ISSUE THREAD

**Issue by ChromeQ** [mmouterde/FlexyTrello#47]
When adding this extension and clicking "authorize" from the FlexyTrello Settings page, then a page displays the following error:
```
Invalid return_url. Wildcard ("*") allowed origins are no longer supported. Contact the developer. See https://community.developer.atlassian.com/t/52093
```

Is it possible to fix this? More info here 
https://community.developer.atlassian.com/t/pure-wildcard-allowed-origins-on-app-keys-will-no-longer-be-recognized-and-will-be-fully-deprecated/52093/26

**Comment by mmouterde** [comment]
Thanks for reporting. This should be fixed, please let me know if the error persists.

**Comment by ChromeQ** [comment]
Apologies on the delay, but just want to confirm the authorize link is working again as expected, as is the persistence over refresh (which is what led me to find this out and raise the issue)

Thanks for the quick fix
