### ISSUE TITLE
If a list has a number limit, the + icon is invisible when a list is shrunk

### ISSUE THREAD

**Issue by Maelstromeous** [mmouterde/FlexyTrello#48]
If a list has a column limit set, it displays numbers e.g. 30/20. This is an element located within the list's header as like the below:
![Screenshot 2022-06-24 at 15 59 09](https://user-images.githubusercontent.com/1776058/175562684-f6fbbfbf-87b5-4ccc-a7ec-207254881a14.png)

The above shows no `-` as the extension is disabled as I cannot see the list otherwise.

However once you hide it via the plugin, the + icon is not displayed. Presumably the numbers push the button out of the list's width, thus making it invisible, like the below:
![Screenshot 2022-06-24 at 15 59 56](https://user-images.githubusercontent.com/1776058/175562936-47515678-827e-4e3a-a669-de9758357628.png)

The left list here is one without a limit, the "Next" one contains a limit as illustrated by the first screenshot.

Solution will need to either remove the numbers on the hidden list so your + icon can then show, or somehow add another means to expand the list.

To be clear, **there is no way to expand the list once it's minimized** with the current implementation. The only way to fix it is to disable the plugin.

**Comment by mmouterde** [comment]
Ok I got it. Thanks for reporting.
Unfortunately, chrome and Trello are closed to deprecate FlexyTrello prerequisites.
This extension won't survive to 2022.. In such perspective, I don't plan to support this extension anymore.

**Comment by Maelstromeous** [comment]
Ah that's unfortunate but understandable. Thanks for replying!

**Comment by mmouterde** [comment]
Hi @Maelstromeous 
It seem's I succeed to migrate to a 2023 proof version of the extension.
As far as tried, this issue seem's fixed.
Let me know
