### ISSUE TITLE
Cards not re-ordering

### ISSUE THREAD

**Issue by RoryCodes** [mmouterde/FlexyTrello#49]
Hello,

Recently I've been having an issue with my cards not re-ordering when I extend/narrow my lists. Currently the list shows 2 columns of cards minimum, and does not change when resizing the list. When extending the list the second card column just stretches out to be centered in the list and the cards in the first column don't move. When resizing down to a single column, the list should have the same behavior as default with a scrolling bar on the right side, which isn't happening. I'm using V1.3.18 on Chrome V113.0.5672.64

**Comment by mmouterde** [comment]
duplicate #50
Let me know if the fix does not cover your case.

**Comment by RoryCodes** [comment]
I can confirm that version 1.3.19 fixed the issue, thank you for the quick response and fix.
