### ISSUE TITLE
Flexy Trello - Scroll no longer works & re-size creates wierd looking view

### ISSUE THREAD

**Issue by SteeleCPAs** [mmouterde/FlexyTrello#50]
Using Chrome - A few days ago the scroll no longer works on the card view.  If you widen a list to 2 or mor cards wide, it scrambles the cards and the scroll bar dissapears.

If we disable Flexy Trello, everything works, but we are limited to 1 card width for viewing.

Is there a fix?  I tried removing and re-adding the extension.

Thank you!

**Comment by mmouterde** [comment]
Hi,
Thanks for reporting.
A fix is in review by Google Team before publishing.

**Comment by SteeleCPAs** [comment]
I do not see where the "Fix" is posted, yet this post was marked completed. The problem persists.  Please share how to apply the "Fix".

**Comment by mmouterde** [comment]
The fix has been delivered on Chrome Web Store as FlexyTrello **1.3.19**.
For instance, it still requires a review by Google Team before been published to every user.
Once publicly published, your Chrome should get the last version automatically.

**Comment by SteeleCPAs** [comment]
Thank you, I will keep my eyes out for it...   ...how long does it typically take for approval?

**Comment by RoryCodes** [comment]
I can confirm that version 1.3.19 fixed the issue
